### PR TITLE
fix cache entry expiration - monotinic vs realtime

### LINKED ISSUE #522: Get returns nothing when TTL set
Hi,

It looks, that it's impossible to get value with `CaffeineCache`, if it was inserted with TTL.

Sample code:

```scala
import cats.effect.{ExitCode, IO, IOApp}
import scalacache.caffeine.CaffeineCache
import scalacache.{Cache, get, put}

object Main extends IOApp {
  val cache: IO[CaffeineCache[IO, String]] = CaffeineCache[IO, String]

  private def testCache(implicit c: Cache[IO, String]): IO[Unit] = for {
  _ <- put("foo")("bar", Some(scala.concurrent.duration.FiniteDuration(10, "days")))
  result <- get("foo")
  _ <- IO(println(result))
  } yield ()

  override def run(args: List[String]): IO[ExitCode] = cache.flatMap(implicit c => testCache.map(_ => ExitCode.Success))
}
```

It prints `None` but it should be `Some(bar)`. If I remove TTL, it works fine. My suspicion is that the following condition can be incorrect: https://github.com/cb372/scalacache/blob/1fb5879310a316553609ba4b026bb9089788eea7/modules/caffeine/src/main/scala/scalacache/caffeine/CaffeineCache.scala#L34

### PR DESCRIPTION
**Pull request by yurique**
Fixes #522

### CODE REVIEW

**Comment by yurique** [comment]
The tests make sense to me, but would be great if someone could double-check :)

**Review by kubukoz — APPROVED** [review]

File: modules/caffeine/src/test/scala/scalacache/caffeine/CaffeineCacheSpec.scala [hunk 1]
```diff
@@ -114,4 +127,24 @@ class CaffeineCacheSpec extends AnyFlatSpec with Matchers with BeforeAndAfter wi
...
+  it should "store the given key-value pair in the underlying cache with no TTL, then get it back" in ticked { _ =>
+    val underlying = newCCache
+    val cache      = newIOCache(underlying)
+    cache.put("key1")("hello", None) *>
+      cache.get("key1").map { _ shouldBe defined }
+  }
+
+  behavior of "get put with TTL"
+
+  it should "store the given key-value pair in the underlying cache with the given TTL, then get it back when not expired" in ticked {
```
Comment (kubukoz) [inline modules/caffeine/src/test/scala/scalacache/caffeine/CaffeineCacheSpec.scala:141]: Let's have another one like this, but with an `IO.sleep` between put and get. It'll be instant because of how `ticked` works.

**Comment by kubukoz** [comment]
Thanks! I always mix up the two kinds of clocks, this whole thing reminded me what the difference is 😅

File: modules/caffeine/src/test/scala/scalacache/caffeine/CaffeineCacheSpec.scala (hunk 1 above)
Comment (yurique) [reply modules/caffeine/src/test/scala/scalacache/caffeine/CaffeineCacheSpec.scala]: Added a couple of tests with sleep.

**Review by kubukoz — APPROVED** [review]

**Comment by kubukoz** [comment]
Think we could remove expired keys if we read one, as a space optimization - but that can be a different PR :)
